version: '3.9'
services:
  smartfarmmanager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8088:8080' # Map HTTP từ container (8080) ra host (8088)
      - '8888:8081' # Map HTTPS từ container (8081) ra host (8888)
    environment:
      - SECRET_KEY=adjkasdbyuaasgcndsjfngljkdsjflgsdfklgnslkdfnslkdnfkjsahdfkjsahjlkfsa
    restart: unless-stopped
